# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mk_log_config = debug
  mk_args_config = debug
  mk_fs_config = debug
  mk_stb_config = debug
  mk_sokol_config = debug
  mk_sqt_config = debug

else ifeq ($(config),release)
  mk_log_config = release
  mk_args_config = release
  mk_fs_config = release
  mk_stb_config = release
  mk_sokol_config = release
  mk_sqt_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := mk_log mk_args mk_fs mk_stb mk_sokol mk_sqt

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mk_log:
ifneq (,$(mk_log_config))
	@echo "==== Building mk_log ($(mk_log_config)) ===="
	@${MAKE} --no-print-directory -C BUILD -f mk_log.make config=$(mk_log_config)
endif

mk_args:
ifneq (,$(mk_args_config))
	@echo "==== Building mk_args ($(mk_args_config)) ===="
	@${MAKE} --no-print-directory -C BUILD -f mk_args.make config=$(mk_args_config)
endif

mk_fs:
ifneq (,$(mk_fs_config))
	@echo "==== Building mk_fs ($(mk_fs_config)) ===="
	@${MAKE} --no-print-directory -C BUILD -f mk_fs.make config=$(mk_fs_config)
endif

mk_stb:
ifneq (,$(mk_stb_config))
	@echo "==== Building mk_stb ($(mk_stb_config)) ===="
	@${MAKE} --no-print-directory -C BUILD -f mk_stb.make config=$(mk_stb_config)
endif

mk_sokol:
ifneq (,$(mk_sokol_config))
	@echo "==== Building mk_sokol ($(mk_sokol_config)) ===="
	@${MAKE} --no-print-directory -C BUILD -f mk_sokol.make config=$(mk_sokol_config)
endif

mk_sqt:
ifneq (,$(mk_sqt_config))
	@echo "==== Building mk_sqt ($(mk_sqt_config)) ===="
	@${MAKE} --no-print-directory -C BUILD -f mk_sqt.make config=$(mk_sqt_config)
endif

clean:
	@${MAKE} --no-print-directory -C BUILD -f mk_log.make clean
	@${MAKE} --no-print-directory -C BUILD -f mk_args.make clean
	@${MAKE} --no-print-directory -C BUILD -f mk_fs.make clean
	@${MAKE} --no-print-directory -C BUILD -f mk_stb.make clean
	@${MAKE} --no-print-directory -C BUILD -f mk_sokol.make clean
	@${MAKE} --no-print-directory -C BUILD -f mk_sqt.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mk_log"
	@echo "   mk_args"
	@echo "   mk_fs"
	@echo "   mk_stb"
	@echo "   mk_sokol"
	@echo "   mk_sqt"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"